# Generated by Django 4.2.14 on 2024-08-13 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingform',
            name='guests',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
