# Generated by Django 4.2.14 on 2024-08-14 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_date', to='booking.bookingform')),
                ('guests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_guests', to='booking.bookingform')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_name', to='booking.bookingform')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.table')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_time', to='booking.bookingform')),
            ],
        ),
    ]
