# Generated by Django 4.2.14 on 2024-08-15 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_bookingassignment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingassignment',
            name='time',
        ),
        migrations.AlterField(
            model_name='bookingassignment',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingassignment',
            name='guests',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookingassignment',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
