# Generated by Django 4.2.14 on 2024-08-15 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_bookingassignment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingassignment',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
            preserve_default=False,
        ),
    ]
