# Generated by Django 4.2.14 on 2024-08-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_bookingassignment_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingAssignment',
        ),
    ]
