# Generated by Django 4.2.14 on 2024-08-15 13:57

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_bookingassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingassignment',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingform',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2024, 8, 15, 13, 57, 57, 284489, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
