# Generated by Django 4.2.14 on 2024-08-15 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_bookingassignment_end_time_bookingform_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingassignment',
            name='end_time',
        ),
    ]
