# Generated by Django 4.2.14 on 2024-08-16 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_reserved',
        ),
        migrations.RemoveField(
            model_name='table',
            name='reserved_by',
        ),
        migrations.DeleteModel(
            name='BookingAssignment',
        ),
    ]
