# Generated by Django 4.2.14 on 2024-08-17 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0013_remove_table_is_reserved_remove_table_reserved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingform',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
